spring:

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddlAuto: validate
    open-in-view: false

  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: '*'

cors:
  origins:
    - https://vaadin-apartments-prod.herokuapp.com
